#!/usr/bin/env node
/** Aggregate gpu-tests/results/*.json into a markdown table -> gpu-tests/RESULTS.md */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const dir = "gpu-tests/results";
const rows = readdirSync(dir).filter((f) => f.endsWith(".json")).map((f) => JSON.parse(readFileSync(`${dir}/${f}`, "utf8")));

const order = ["qwen3-embedding-0.6b", "qwen3-vl-8b", "gpt-oss-20b", "glm-4.7-flash", "qwen3-vl-30b", "qwen3-vl-32b", "qwen3-coder-next", "gpt-oss-120b"];
rows.sort((a, b) => (order.indexOf(a.model) - order.indexOf(b.model)));

const num = (n) => (n == null ? "-" : String(n));
const line = (r) => {
  if (r.kind === "embed")
    return `| ${r.model} | ${r.gpu} | ${num(r.vram_gb)} GB | embed (${r.embedding_dim}-dim) | ${num(r.total_seconds)}s | instant | ${num(r.pull_seconds)}s | ${r.fits_120s_budget ? "yes" : "NO"} |`;
  return `| ${r.model} | ${r.gpu} | ${num(r.vram_gb)} GB | ${num(r.tokens_per_sec)} tok/s | ${num(r.cold_total_seconds)}s | ${num(r.warm_total_seconds)}s | ${num(r.pull_seconds)}s | ${r.warm_fits_120s_budget ? "yes" : "NO"} |`;
};

const md = `# Measured GPU test results

Real runs on rented RunPod GPUs via Ollama (the engine Lightchain workers use). Each model was pulled, then run with a fixed prompt; "warm" = model already resident. "Fits 120s" is for the *warm* run at the tested output length; see notes for models whose real-length output would exceed the budget.

| Model | GPU | Peak VRAM | Throughput | Cold (incl. load) | Warm | One-time pull | Fits 120s |
|---|---|---|---|---|---|---|---|
${rows.map(line).join("\n")}

Notes:
- VRAM is the resident size reported by Ollama (\`/api/ps\`), i.e. weights + KV/context.
- \`qwen3-vl:8b\` used ~9.5 GB, so it needs a 12 GB card, not the 8 GB minimum.
- \`qwen3-vl:32b\` (dense) ran at only ~3 tok/s on a 24 GB card: a full 4096-token answer would take ~20 min, far past the 120 s budget. Use the MoE \`qwen3-vl:30b\` on 24 GB, or run the 32B on an 80 GB card.
- Pull time is a one-time per-worker download; it is not part of a job's compute window.

Generated by \`gpu-tests/summarize.mjs\` from \`gpu-tests/results/*.json\`.
`;
writeFileSync("gpu-tests/RESULTS.md", md);
console.log("wrote gpu-tests/RESULTS.md with", rows.length, "models");
console.log(md);
